spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3311/securecapita_db
    password: letmein
    username: root
  jpa:
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quoted_indentifiers: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 16000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
  profiles:
#    active: ${ACTIVE_PROFILE:dev}
    active: dev
application:
  title: Secure Capita
  version: 1.0

#SERVER_PORT: 8097
#server:
#  port: ${SERVER_PORT:8097}

SERVER_PORT: 8097

EMAIL_HOST: smpt.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ngom3793@gmail.com
EMAIL_PASSWORD: zlcl qfyo jpbb rpwt
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}