spring:
#  profiles:
#    active: ${ACTIVE_PROFILE:test}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://127.0.0.1:3311/securecapita_db
    password: letmein
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
server:
  port: 8097

ACTIVE_PROFILE: test

EMAIL_HOST: smpt.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ngom3793@gmail.com
EMAIL_PASSWORD: zlcl qfyo jpbb rpwt
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}